XPos/XPos.Web/Controllers/UploadFileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XPos.DataModel;
using XPos.Repository;

namespace XPos.Web.Controllers
{
    public class UploadFileController : Controller
    {
        // GET: UploadFile
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return PartialView("_Create");
        }

        public ActionResult List(int page = 1, int perPage = 8)
        {
            Pagination pg = UploadFileRepo.Paging(page, perPage);
            ViewBag.PageCount = pg.Pages;
            return PartialView("_List", pg.ListOf);
        }

        [HttpPost]
        public ActionResult Create(HttpPostedFileBase file, FileCollection model)
        {
            if (file != null && file.ContentLength > 0)
            {
                try
                {
                    string[] fileName = file.FileName.Split('.');
                    string newFileName = DateTime.Now.ToString("yyyyMMddHHmmss") + "." + fileName[fileName.Length - 1];
                    string path = Path.Combine(Server.MapPath("~/UploadFileFoto"), Path.GetFileName(newFileName));
                    file.SaveAs(path);
                    model.FileName = newFileName;
                    ResponseResult result = UploadFileRepo.Update(model);

                    return Json(new
                    {
                        success = result.Success,
                        message = result.Message,
                        entity = result.Entity
                    }, JsonRequestBehavior.AllowGet);
                }
                catch (Exception ex)
                {
                    return Json(new
                    {
                        success = false,
                        message = ex.Message
                    }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(new
                {
                    success = false,
                    message = "You have no specified a file"
                }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

XPos/XPos.Web/Views/UploadFile/Index.cshtml
@{
    ViewBag.Title = "Upload File";
}

<h2>@ViewBag.Title Galery</h2>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
            <input type="button" class="btn btn-success" id="btn-create" value="Create New" />
            <input type="button" class="btn btn-warning" id="btn-prev" value="< Prev" />
            <input type="button" class="btn btn-warning" id="btn-next" value="Next >" />
        </h3>
    </div>
    <div class="panel-body">
        Loading...
    </div>
</div>

<div id="modal1" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

@section Scripts{
    <script type="text/javascript">
        var currPage = 1;
        var maxPage = 1;
        $(document).ready(function () {
            GetList(currPage)
        })

        function GetList(pg) {
            $.ajax({
                url: '@Url.Action("List", "UploadFile")',
                type: 'get',
                data: { page: currPage, perPage: 8 }, /*Ngatur Foto*/
                success: function (result) {
                    $(".panel-body").html(result);
                }
            });
        }

        $("#btn-create").click(function () {
            $.ajax({
                url: '@Url.Action("Create", "UploadFile")',
                type: 'get',
                success: function (result) {
                    $(".modal-body").html(result);
                    $(".modal").modal("show");
                }
            });
        })

        $("#btn-prev").click(function () {
            if (currPage > 1) {
                currPage--;
            }
            GetList(currPage);
        });

        $("#btn-next").click(function () {
            if (currPage < maxPage) {
                currPage++;
            }
            GetList(currPage);
        });
    </script>
}

XPos/XPos.Web/Views/UploadFile/_Create.cshtml
@model XPos.DataModel.FileCollection


@using (Html.BeginForm("Create", "UploadFile", FormMethod.Post, new { id = "form-create", name = "form-create", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="selectedfile" id="selectedfile" class="btn btn-default" onchange="showPreview(this)" />
                <br />
                <img src="~/UploadFileFoto/no-image.png" alt="No Image" id="img-preview" width="200px" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Active)
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Cancel" data-dismiss="modal" class="btn btn-default" />
                <input type="button" value="Upload File" id="upload-file" class="btn btn-success" />
            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
        $("#upload-file").click(function () {
            var formData = new FormData();

            formData.append("file", $('#selectedfile')[0].files[0]);

            var other_data = $("#form-create").serializeArray();

            $.each(other_data, function (key, input) {
                formData.append(input.name, input.value);
            });

            $.ajax({
                url: '@Url.Action("Create", "UploadFile")',
                type: 'post',
                data: formData,
                contentType: false,
                processData: false,
                success: function (result) {
                    if (result.success) {
                        var ent = result.entity;
                        alert(`Save successful\nTitle: ${ent.Title}, File Name: ${ent.FileName}`);
                        $("#modal1").modal("hide");
                        GetList();
                    } else {
                        alert(`Error: ${result.message}`);
                    }
                }
            })
            return false;
        })

        function showPreview(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $("#img-preview").attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }
</script>

XPos/XPos.Web/Views/UploadFile/_List.cshtml
@model IEnumerable<XPos.DataModel.FileCollection>
@{
    int colCnt = 4;
}
Page count : @ViewBag.PageCount
@foreach (var item in Model)
{
    if (colCnt == 4)
    {
        colCnt = 0;
        @:<div class="row">
        }
        <div class="col-xs-3">
            Title: @Html.DisplayFor(modelItem => item.Title)<br />
            File: @Html.DisplayFor(modelItem => item.FileName)<br />
            <img src="~/UploadFileFoto/@item.FileName" alt="Sample Image" width="100" />
            <div class="form-group">
                @Html.LabelFor(modelItem => item.Active)
                @Html.DisplayFor(modelItem => item.Active)
            </div>
        </div>
        if (colCnt == 3)
        {
        @: </div>
    }
    colCnt++;
}


<script type="text/javascript">
    $(document).ready(function () {
        maxPage = @ViewBag.PageCount;
    })
</script>